PLMVC/Controllers/ArtistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class ArtistaController : Controller
    {
        // GET: Artista
        public ActionResult GetAll()
        {
            ML.Artista artista = new ML.Artista();
            ML.Result result = BL.Artista.GetAllEF();

            if (result.Correct )
            {
                artista.Artistas = result.Objects;
            }

            return View(artista);
        }

        [HttpGet]
        public ActionResult Form(int? idArtista)
        {
            ML.Artista artista = new ML.Artista();

            if ( idArtista != null )
            {
                
                ML.Result resultArtista = BL.Artista.GetById(idArtista.Value);

                if (resultArtista.Correct)
                {
                    artista = (ML.Artista)resultArtista.Object;
                }
            }
            return View(artista);
        }

        [HttpPost]  
        public ActionResult Form(ML.Artista artista)
        {

            if (artista.IdArtista == 0)
            {
                ML.Result result = BL.Artista.Add(artista);

                if (result.Correct )
                {
                    ViewBag.Message = "REGISTRO AGREGADO EXITOSAMENTE";
                }
                else
                {
                    ViewBag.Message = "ERROR, REGISTRO NO AGREGADO";
                }
            }
            else
            {
                ML.Result result = BL.Artista.Update(artista);

                if (result.Correct)
                {
                    ViewBag.Message = "REGISTRO ACTUALIZADO EXITOSAMENTE";
                }
                else
                {
                    ViewBag.Message = "ERROR, REGISTRO NO ACTUALIZADO";
                }
            }

            return PartialView("Modal");
        }


        public ActionResult Delete (int idArtista)
        {
            ML.Result result = BL.Artista.Delete(idArtista);

            if (result.Correct)
            {
                ViewBag.Message = "REGISTRO ELIMINADO EXITOSAMENTE";
            }
            else
            {
                ViewBag.Message = "ERROR, REGISTRO NO ELIMINADO";
            }

            return PartialView("Modal");
        }
        
    }
}

PLMVC/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class DiscoController : Controller
    {
        // GET: Disco
        public ActionResult GetAll()
        {
            ML.Result result = BL.Disco.GetAll();
            ML.Disco disco = new ML.Disco();

            if (result.Correct)
            {               
                disco.Discos = result.Objects;
            }
            return View(disco);
        }


        [HttpGet]
        public ActionResult Form(int? idDisco)
        {
            ML.Disco disco = new ML.Disco();
            disco.Artista = new ML.Artista();
            disco.Distribuidora = new ML.Distribuidora();
            disco.Genero = new ML.Genero();

            ML.Result resultArtista = BL.Artista.GetAllEF();
            ML.Result resultGenero = BL.Genero.GetAllEF();
            ML.Result resultDistribuidora = BL.Distribuidora.GetAllEF();

            if (idDisco != null) 
            {
                ML.Result resultUpdate = BL.Disco.GetById(idDisco.Value);

                if (resultUpdate.Correct)
                {
                    disco = (ML.Disco)resultUpdate.Object;
                    disco.Artista.Artistas = resultArtista.Objects;
                    disco.Genero.Generos = resultGenero.Objects;
                    disco.Distribuidora.Distribuidoras = resultDistribuidora.Objects;
                }
                return View(disco);
            }
            else
            {
                disco.Artista.Artistas = resultArtista.Objects;
                disco.Genero.Generos = resultGenero.Objects;
                disco.Distribuidora.Distribuidoras = resultDistribuidora.Objects;
                return View(disco);
            }      
        }

        [HttpPost]
        public ActionResult Form(ML.Disco disco)
        {
            ML.Result result = new ML.Result();

            if (disco.IdDisco == 0)
            {
                result = BL.Disco.Add(disco);

                if (result.Correct)
                {
                    ViewBag.Message = "INSERTADO CORRECTAMENTE";
                }
                else
                {
                    ViewBag.Message = "ERROR, RESGISTRO NO INSERTADO";
                }

            }
            else
            {
                result = BL.Disco.Update(disco);

                if (result.Correct)
                {
                    ViewBag.Message = "ACTUALIZACION EXITOSA";
                }
                else
                {
                    ViewBag.Message = "ERROR, REGISTRO NO ACTUALIZADO";
                }

            }

            return PartialView("Modal");
        }

        public ActionResult Delete (int idDisco)
        {
            ML.Result result = BL.Disco.Delete(idDisco);

            if (result.Correct)
            {
                ViewBag.Message = "REGISTRO ELIMINADO EXITOSAMENTE";
            }
            else
            {
                ViewBag.Message = "ERROR, REGISTRO NO ELIMINADO";
            }

            return PartialView("Modal");
        }
    }
}

PLMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PLMVC/Views/Artista/Form.cshtml
@model ML.Artista
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RELLENE LOS CAMPOS</h2>
<br />
@using (Html.BeginForm("Form", "Artista", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.IdArtista)

    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.Nombre)
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.ApellidoPaterno)
            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.ApellidoMaterno)
            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.FechaNacimiento)
            @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", @Type = "date" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.NombreArtistico)
            @Html.TextBoxFor(model => model.NombreArtistico, new { @class = "form-control" })
        </div>

    </div>
    <br />
    <button class="btn btn-success" type="submit">HECHO</button>
    <a href="@Url.Action("GetAll", "Artista")" class="btn btn-warning">VOLVER</a>
}

PLMVC/Views/Artista/GetAll.cshtml
@model ML.Artista
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista General de Artistas</h2>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>EDITAR </th>
                <th>ELIMINAR </th>
                <th>ID ARTISTA </th>
                <th>NOMBRE </th>
                <th>APELLIDO PATERNO </th>
                <th>APELLIDO MATERNO </th>
                <th>FECHA NACIMIENTO </th>
                <th>PSEUDONIMO </th>
            </tr>
        </thead>
        <tbody>
            @foreach(ML.Artista registro in Model.Artistas)
            {
                <tr>
                    <td>  <a href="@Url.Action("Form", "Artista", new {idArtista = registro.IdArtista})" class="btn btn-primary">EDITAR</a> </td>
                    <td> <a href="@Url.Action("Delete","Artista", new {idArtista = registro.IdArtista})" onclick=" return confirm('SEGURO QUE DESEAS ELIMINARLO?');" class="btn btn-danger">ELIMINAR</a> </td>
                    <td>@registro.IdArtista </td>
                    <td>@registro.Nombre </td>
                    <td>@registro.ApellidoPaterno </td>
                    <td>@registro.ApellidoMaterno </td>
                    <td>@registro.FechaNacimiento </td>
                    <td>@registro.NombreArtistico </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <a href="@Url.Action("Form","Artista")" class="btn btn-outline-success">AGREGAR NUEVO ARTISTA</a>
    <a href="@Url.Action("GetAll", "Disco")" class="btn btn-warning"> VOLVER</a>
</div>

PLMVC/Views/Artista/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5> <!--"Message debe ser el mismo nombre que en las ViewBags de mi controlador"-->
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@

                @Html.ActionLink("Vale", "GetAll", "Artista", htmlAttributes: new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PLMVC/Views/Disco/Form.cshtml
@model ML.Disco
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LLENA LOS CAMPOS</h2>
<hr />

@using (Html.BeginForm("Form", "Disco", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.IdDisco)

    <br />
    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.Titulo)
            @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Duracion)
            @Html.TextBoxFor(model => model.Duracion, new { @class = "form-control", @Type ="time" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Año)
            @Html.TextBoxFor(model => model.Año, new { @class = "form-control", @Type = "date" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.Ventas)
            @Html.TextBoxFor(model => model.Ventas, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Disponibilidad)
            @Html.TextBoxFor(model => model.Disponibilidad, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.Artista)
            @Html.DropDownListFor(model => model.Artista.IdArtista, new SelectList(Model.Artista.Artistas,"IdArtista", "NombreArtistico"), "SELECCIONA UNA OPCION", new {@class="form-control"});
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Genero)
            @Html.DropDownListFor(model => model.Genero.IdGenero, new SelectList(Model.Genero.Generos,"IdGenero", "Nombre"), "SELECCIONA OPCION", new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.LabelFor(model => model.Distribuidora)
            @Html.DropDownListFor(model => model.Distribuidora.IdDistribuidora, new SelectList(Model.Distribuidora.Distribuidoras,"IdDistribuidora", "Nombre"), "SELECCIONA OPCION", new { @class = "form-control" })
        </div>
    </div>

    <button class="btn btn-success" type="submit"> HECHO </button>
    <a class="btn btn-warning" href="@Url.Action("GetAll", "Disco")">VOLVER</a>
}

PLMVC/Views/Disco/GetAll.cshtml
@model ML.Disco
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LISTA GENERAL DE DISCOS</h2>
<hr />

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead class="table-striped table-light">
            <tr>
                <th>EDITAR</th>
                <th>ELIMINAR</th>
                <th>ID DISCO</th>
                <th>TITULO DISCO</th>
                <th>DURACION</th>
                <th>AÑO CREACION</th>
                <th>DISPONIBILIDAD</th>
                <th>VENTAS</th>
                <th>ID ARTISTA</th>
                <th>ARTISTA</th>
                <th>ID DISTRIBUIDORA</th>
                <th>DISTRIBUIDORA</th>
                <th>ID GENERO</th>
                <th>GENERO</th>
            </tr>
        </thead>
        <tbody>
            @foreach(ML.Disco registro in Model.Discos)
            {
                <tr>
                    <td><a href="@Url.Action("Form", "Disco", new {idDisco = registro.IdDisco})" type="button" class="btn btn-warning"> EDITAR </a> </td>
                    <td><a href="@Url.Action("Delete", "Disco", new { idDisco = registro.IdDisco })" onclick=" return confirm('¿Seguro que desea elimiar el registro?');" type="button" class="btn btn-danger"> ELIMINAR </a> </td>
                    <td>@registro.IdDisco </td>
                    <td>@registro.Titulo  </td>
                    <td>@registro.Duracion </td>
                    <td>@registro.Año </td>
                    <td>@registro.Disponibilidad  </td>
                    <td>@registro.Ventas  </td>
                    <td>@registro.Artista.IdArtista  </td>
                    <td>@registro.Artista.NombreArtistico  </td>
                    <td>@registro.Distribuidora.IdDistribuidora </td>
                    <td>@registro.Distribuidora.Nombre </td>
                    <td>@registro.Genero.IdGenero</td>
                    <td>@registro.Genero.Nombre</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="text-right">
    <a href="@Url.Action("Form","Disco")" type="button" class="btn btn-outline-success"> AÑADIR NUEVO DISCO</a>
</div>

PLMVC/Views/Disco/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5> <!--"Message debe ser el mismo nombre que en las ViewBags de mi controlador"-->
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@

                @Html.ActionLink("Vale", "GetAll", "Disco", htmlAttributes: new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PLMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PLMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PLMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PLMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Disco", "GetAll", "Disco", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Artista", "GetAll", "Artista", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>